- name: stop the service
  tags: 
  - deployment
  ansible.builtin.service:  # ansible module to manage services 
    name: "{{ component }}"
    state: stopped

- name: remove /app directory
  ansible.builtin.file: # ansible module to manage files and directories
    state: absent
    path: /app

- name: create /app directory
  ansible.builtin.file: # ansible module to manage files and directories
    state: directory
    path: /app

- name: download application
  ansible.builtin.unarchive: # ansible module to extract files from an archive
    src: "https://roboshop-artifacts.s3.amazonaws.com/{{ component }}-v{{ app_version }}.zip"
    dest: /app
    remote_src: yes

- name: install dependencies
  community.general.npm: # ansible module to manage npm packages
    path: /app

- name: restart {{ component }}
  ansible.builtin.service: # ansible module to manage services
    name: "{{ component }}"
    state: restarted